[package]
name = "spotdiff"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
base64-simd.workspace = true
flate2.workspace = true
clap.workspace = true
image.workspace = true
ratatui.workspace = true
crossterm.workspace = true
ratatui-image.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[example]]
name = "terminal-failure"
path = "tests/support/terminal_failure.rs"
